server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: SMARTWAY-USER-SERVICE
          uri: lb://SMARTWAY-USER-SERVICE
          predicates:
              - Path=/users/**
        - id: SMARTWAY-DEP-SERVICE
          uri: lb://SMARTWAY-DEP-SERVICE
          predicates:
              - Path=/departments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
